### ISSUE TITLE
aarch64 dup2

### ISSUE THREAD

**Issue by r3dlight** [kpcyrd/syscallz-rs#21]
Hi,

May I ask you to add dup2 for aarch64 please ?

Thanks !

**Comment by kpcyrd** [comment]
There is no dup2 syscall on aarch64, if you're calling the `dup2` libc function it's internally using the dup3 syscall instead (with `flags = 0` as the 3rd argument). :)

https://github.com/bminor/musl/blob/718f363bc2067b6487900eddc9180c84e7739f80/src/unistd/dup2.c#L6
https://github.com/bminor/glibc/blob/4290aed05135ae4c0272006442d147f2155e70d7/sysdeps/unix/sysv/linux/dup2.c#L26
https://github.com/rfjakob/gocryptfs/issues/121
https://github.com/ngaut/log/issues/4
