### ISSUE TITLE
resolve Syscall from &str

### ISSUE THREAD

**Issue by Nugine** [kpcyrd/syscallz-rs#8]
I would like to configure seccomp behavior by some texts.
Like the low level `seccomp_syscall_resolve_name` which converts `*const c_char` to `c_int`, a high level function which converts `&str` to `Result<Syscall, Error>` can be useful.

**Comment by kpcyrd** [comment]
Sorry for the late reply, I've published your patch as 0.11.2

**Comment by Nugine** [comment]
Never mind. I'm developing an online judger ([Nugine/carapace](https://github.com/Nugine/carapace.git)) using seccomp. It may depend on more features of this crate. An active dependency helps.
